DROP TABLE Utilisateur CASCADE CONSTRAINT;
DROP TABLE Message CASCADE CONSTRAINT;
DROP TABLE SESSIONS CASCADE CONSTRAINT;
DROP TABLE SYMPATHISER CASCADE CONSTRAINT;
DROP TABLE IDGEN CASCADE CONSTRAINT;